/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/bakery2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bakery2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.window.geometry} material={nodes.window.material} position={[-3.223, 5.199, 7.068]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} />
      <mesh geometry={nodes.swiss1.geometry} material={nodes.swiss1.material} position={[0.293, 4.143, -1.032]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.pumpkincake1.geometry} material={nodes.pumpkincake1.material} position={[0.748, 2.144, 0.537]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.plane.geometry} material={nodes.plane.material} position={[0.47, -0.004, 0]} />
      <mesh geometry={nodes.tiramisured1.geometry} material={nodes.tiramisured1.material} position={[0.363, 4.189, -1.867]} />
      <mesh geometry={nodes.rosecake2.geometry} material={nodes.rosecake2.material} position={[-0.409, 2.119, -0.977]} rotation={[0.55, -0.858, 0.19]} />
      <mesh geometry={nodes.rosecake1.geometry} material={nodes.rosecake1.material} position={[0.71, 2.242, -0.805]} rotation={[1.154, -1.247, 0.679]} />
      <mesh geometry={nodes.bluedonut1.geometry} material={nodes.bluedonut1.material} position={[0.45, 1.943, 1.609]} rotation={[0, 1.284, 0]} />
      <mesh geometry={nodes.pinkdonut1.geometry} material={nodes.pinkdonut1.material} position={[0.529, 2.68, 0.037]} rotation={[0, 1.284, 0]} />
      <mesh geometry={nodes.redvelvet1.geometry} material={nodes.redvelvet1.material} position={[0.602, 2.122, -2.252]} />
      <mesh geometry={nodes.bluecheesecake2.geometry} material={nodes.bluecheesecake2.material} position={[0.633, 2.786, -1.184]} />
      <mesh geometry={nodes.stand.geometry} material={nodes.stand.material} position={[-0.092, 1.261, -0.351]} />
      <mesh geometry={nodes.support.geometry} material={nodes.support.material} position={[0, 1.759, -0.371]} />
      <mesh geometry={nodes.shelf.geometry} material={nodes.shelf.material} position={[0, 3.867, -0.371]} />
      <mesh geometry={nodes.glassbottom.geometry} material={nodes.glassbottom.material} position={[0, 1.904, -0.371]} />
      <mesh geometry={nodes.glass2.geometry} material={nodes.glass2.material} position={[0, 2.638, -0.371]} />
      <mesh geometry={nodes.glass1.geometry} material={nodes.glass1.material} position={[0, 3.33, -0.371]} />
      <mesh geometry={nodes.glasstop.geometry} material={nodes.glasstop.material} position={[0, 3.955, -0.371]} />
      <mesh geometry={nodes.shelfinner.geometry} material={nodes.shelfinner.material} position={[0, 3.867, -0.371]} />
      <mesh geometry={nodes.tiramisured2.geometry} material={nodes.tiramisured2.material} position={[-0.423, 4.415, -1.754]} rotation={[0, -0.547, -1.302]} />
      <mesh geometry={nodes.plate3.geometry} material={nodes.plate3.material} position={[-6.082, 6.668, -0.499]} rotation={[-Math.PI, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.plate2.geometry} material={nodes.plate2.material} position={[-6.048, 6.251, 1.099]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.chocodonut1.geometry} material={nodes.chocodonut1.material} position={[0.257, 3.996, 1.024]} />
      <mesh geometry={nodes.whitedonut1.geometry} material={nodes.whitedonut1.material} position={[0.538, 3.383, -1.034]} />
      <mesh geometry={nodes.swiss3.geometry} material={nodes.swiss3.material} position={[0.643, 3.528, 1.156]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.swiss4.geometry} material={nodes.swiss4.material} position={[-0.407, 3.528, 1.156]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.swiss5.geometry} material={nodes.swiss5.material} position={[0.498, 2.834, -2.126]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.tiramisuchoc1.geometry} material={nodes.tiramisuchoc1.material} position={[0.441, 3.364, 0.121]} />
      <mesh geometry={nodes.cupcake1.geometry} material={nodes.cupcake1.material} position={[0.446, 3.597, -2.075]} rotation={[-Math.PI, 1.068, -Math.PI]} />
      <mesh geometry={nodes.redvelvet2.geometry} material={nodes.redvelvet2.material} position={[-0.871, 2.122, -2.252]} />
      <mesh geometry={nodes.bluecheesecake1.geometry} material={nodes.bluecheesecake1.material} position={[-0.434, 2.786, -1.184]} />
      <mesh geometry={nodes.pumpkincake2.geometry} material={nodes.pumpkincake2.material} position={[-0.176, 2.144, 0.537]} rotation={[0, 1.571, 0]} />
      <mesh geometry={nodes.curtain.geometry} material={nodes.curtain.material} position={[-2.043, 4.521, 6.534]} rotation={[-Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.swiss5001.geometry} material={nodes.swiss5001.material} position={[-0.54, 2.834, -2.126]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.bluedonut1001.geometry} material={nodes.bluedonut1001.material} position={[-0.573, 1.943, 1.609]} rotation={[0, 1.284, 0]} />
      <mesh geometry={nodes.kitkatcake2.geometry} material={nodes.kitkatcake2.material} position={[-0.611, 2.773, 1.186]} />
      <mesh geometry={nodes.pinkdonut1001.geometry} material={nodes.pinkdonut1001.material} position={[-0.696, 2.68, 0.037]} rotation={[0, 1.284, 0]} />
      <mesh geometry={nodes.cupcake2.geometry} material={nodes.cupcake2.material} position={[-0.537, 3.597, -2.075]} rotation={[0, -1.068, 0]} />
      <mesh geometry={nodes.whitedonut1001.geometry} material={nodes.whitedonut1001.material} position={[-0.479, 3.383, -1.034]} />
      <mesh geometry={nodes.tiramisuchoc1001.geometry} material={nodes.tiramisuchoc1001.material} position={[-0.318, 3.364, 0.121]} />
      <mesh geometry={nodes.swiss1001.geometry} material={nodes.swiss1001.material} position={[-0.613, 4.143, -1.032]} rotation={[0, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.kitkatcake1.geometry} material={nodes.kitkatcake1.material} position={[0.446, 2.773, 1.186]} />
      <mesh geometry={nodes.croissant2.geometry} material={nodes.croissant2.material} position={[-0.628, 4.056, -0.056]} rotation={[-Math.PI / 2, -Math.PI / 6, 0]} />
      <mesh geometry={nodes.croissant1.geometry} material={nodes.croissant1.material} position={[0.174, 4.056, -0.056]} rotation={[-Math.PI / 2, -Math.PI / 6, 0]} />
      <mesh geometry={nodes.chocodonut1001.geometry} material={nodes.chocodonut1001.material} position={[-0.674, 3.996, 1.024]} />
      <mesh geometry={nodes.wall.geometry} material={nodes.wall.material} position={[0.499, -0.004, 0]} />
      <mesh geometry={nodes.plate1.geometry} material={nodes.plate1.material} position={[-6.027, 5.74, 2.723]} rotation={[0, 0, -Math.PI / 2]} scale={0.016} />
    </group>
  )
}

useGLTF.preload('/bakery2.gltf')
